MotocycleShop/Controllers/KhoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MotocycleShop.Data;
using MotocycleShop.Models;

namespace MotocycleShop.Controllers
{
    public class KhoesController : Controller
    {
        private readonly MotocycleShopContext _context;

        public KhoesController(MotocycleShopContext context)
        {
            _context = context;
        }

        // GET: Khoes
        public async Task<IActionResult> Index(string khoPhanKhuc, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> phankhucQuery = from b in _context.Kho
                                               orderby b.PhanKhuc
                                               select b.PhanKhuc;
            var khoes = from b in _context.Kho
                        select b;
            if (!string.IsNullOrEmpty(searchString))
            {
                khoes = khoes.Where(s => s.Ten!.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(khoPhanKhuc))
            {
                khoes = khoes.Where(x => x.PhanKhuc == khoPhanKhuc);
            }
            var khoPhanKhucVM = new KhoPhanKhucViewModel
            {
                PhanKhuc = new SelectList(await
            phankhucQuery.Distinct().ToListAsync()),
                Khoes = await khoes.ToListAsync()
            };
            return View(khoPhanKhucVM);
        }

        public async Task<IActionResult> User(string khoPhanKhuc, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> phankhucQuery = from b in _context.Kho
                                               orderby b.PhanKhuc
                                               select b.PhanKhuc;
            var khoes = from b in _context.Kho
                        select b;
            if (!string.IsNullOrEmpty(searchString))
            {
                khoes = khoes.Where(s => s.Ten!.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(khoPhanKhuc))
            {
                khoes = khoes.Where(x => x.PhanKhuc == khoPhanKhuc);
            }
            var khoPhanKhucVM = new KhoPhanKhucViewModel
            {
                PhanKhuc = new SelectList(await
            phankhucQuery.Distinct().ToListAsync()),
                Khoes = await khoes.ToListAsync()
            };
            return View(khoPhanKhucVM);
        }

        // GET: Khoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kho = await _context.Kho
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kho == null)
            {
                return NotFound();
            }

            return View(kho);
        }

        public async Task<IActionResult> UserDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kho = await _context.Kho
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kho == null)
            {
                return NotFound();
            }

            return View(kho);
        }
        // GET: Khoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Khoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ten,NgayNhap,PhanKhuc,Gia,Loai")] Kho kho)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kho);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kho);
        }

        // GET: Khoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kho = await _context.Kho.FindAsync(id);
            if (kho == null)
            {
                return NotFound();
            }
            return View(kho);
        }

        // POST: Khoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ten,NgayNhap,PhanKhuc,Gia,Loai")] Kho kho)
        {
            if (id != kho.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kho);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhoExists(kho.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kho);
        }

        // GET: Khoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kho = await _context.Kho
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kho == null)
            {
                return NotFound();
            }

            return View(kho);
        }

        // POST: Khoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kho = await _context.Kho.FindAsync(id);
            _context.Kho.Remove(kho);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhoExists(int id)
        {
            return _context.Kho.Any(e => e.Id == id);
        }
    }
}

MotocycleShop/Views/Khoes/Create.cshtml
@model MotocycleShop.Models.Kho

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo Mới</h1>

<h4>Kho</h4>
<hr />
<div class="row" >
    <div class="col-md-4" style="border:double" >
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayNhap" class="control-label"></label>
                <input asp-for="NgayNhap" class="form-control" />
                <span asp-validation-for="NgayNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhanKhuc" class="control-label"></label>
                <input asp-for="PhanKhuc" class="form-control" />
                <span asp-validation-for="PhanKhuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Loai" class="control-label"></label>
                <input asp-for="Loai" class="form-control" />
                <span asp-validation-for="Loai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở Về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MotocycleShop/Views/Khoes/Delete.cshtml
@model MotocycleShop.Models.Kho

@{
    ViewData["Title"] = "Xóa";
}

<h1>Xóa</h1>

<h3>Bạn có chắc là bạn muốn xóa?</h3>
<div>
    <h4>Kho</h4>
    <hr />
    <dl class="row" style="border:double">
        <dt class = "col-sm-2">
            Tên
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            Ngày Nhập
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayNhap)
        </dd>
        <dt class = "col-sm-2">
            Phân Khúc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhanKhuc)
        </dd>
        <dt class = "col-sm-2">
            Giá
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Trở Về</a>
    </form>
</div>

MotocycleShop/Views/Khoes/Details.cshtml
@model MotocycleShop.Models.Kho

@{
    ViewData["Title"] = "Chi Tiết";
}

<h1>Chi Tiết</h1>

<div>
    <h4>Kho</h4>
    <hr />
    <dl class="row" style="border:double">
        <dt class = "col-sm-2">
            Tên
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            Ngày Nhập
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayNhap)
        </dd>
        <dt class = "col-sm-2">
            Phân Khúc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhanKhuc)
        </dd>
        <dt class = "col-sm-2">
            Giá
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Sửa</a> |
    <a asp-action="Index">Trở Về</a>
</div>

MotocycleShop/Views/Khoes/Edit.cshtml
@model MotocycleShop.Models.Kho

@{
    ViewData["Title"] = "Sửa";
}

<h1>Sửa</h1>

<h4>Kho</h4>
<hr />
<div class="row">
    <div class="col-md-4" style="border:double">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayNhap" class="control-label"></label>
                <input asp-for="NgayNhap" class="form-control" />
                <span asp-validation-for="NgayNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhanKhuc" class="control-label"></label>
                <input asp-for="PhanKhuc" class="form-control" />
                <span asp-validation-for="PhanKhuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở Về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MotocycleShop/Views/Khoes/Index.cshtml
@model MotocycleShop.Models.KhoPhanKhucViewModel


@{
    ViewData["Title"] = "Kho";
}

<h1>Kho</h1>

<p>
    <a asp-action="Create">Tạo Mới</a>
</p>
<form asp-controller="Khoes" asp-action="Index" method="get">
    <p>
        <select asp-for="KhoPhanKhuc" asp-items="Model.PhanKhuc">
            <option value="">All</option>
        </select>
        Tên: <input type="text" name="SearchString" />
        <input type="submit" value="Tìm" />
    </p>
</form>
<table class="table" style="border:double">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].NgayNhap)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].PhanKhuc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].Gia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].Loai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Khoes)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayNhap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhanKhuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Loai)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Chi Tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Xóa</a>
            </td>
        </tr>
        }
    </tbody>
</table>

MotocycleShop/Views/Khoes/User.cshtml
@model MotocycleShop.Models.KhoPhanKhucViewModel


@{
    ViewData["Title"] = "Kho";
}

<h1>Kho</h1>

<p>
    <a asp-action="Create">Tạo Mới</a>
</p>
<form asp-controller="Khoes" asp-action="User" method="get">
    <p>
        <select asp-for="KhoPhanKhuc" asp-items="Model.PhanKhuc">
            <option value="">All</option>
        </select>
        Tên: <input type="text" name="SearchString" />
        <input type="submit" value="Tìm" />
    </p>
</form>
<table class="table" style="border:double">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].NgayNhap)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].PhanKhuc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoes[0].Gia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Khoes)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayNhap)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhanKhuc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gia)
                </td>
                <td>
                    
                    <a asp-action="UserDetails" asp-route-id="@item.Id">Chi Tiết</a> 
                   
                </td>
            </tr>
        }
    </tbody>
</table>

MotocycleShop/Views/Khoes/UserDetails.cshtml
@model MotocycleShop.Models.Kho

@{
    ViewData["Title"] = "Chi Tiết";
}

<h1>Chi Tiết</h1>

<div>
    <h4>Kho</h4>
    <hr />
    <dl class="row" style="border:double">
        <dt class="col-sm-2">
            Tên
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            Ngày Nhập
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NgayNhap)
        </dd>
        <dt class="col-sm-2">
            Phân Khúc
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhanKhuc)
        </dd>
        <dt class="col-sm-2">
            Giá
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
    </dl>
</div>
<div>
  
    <a asp-action="User">Trở Về</a>
</div>